import { defineProblem } from "@/lib/problem-template";

export const keplerConjecture = defineProblem({
  slug: "kepler-conjecture",
  title: "Kepler Conjecture",
  status: "proved",
  field: "geometry",
  year: 1998,
  shortDescription:
      "The densest packing of equal spheres is the familiar cannonball stacking arrangement.",
  longDescription:
      "In 1611 Kepler conjectured that no arrangement of equal spheres in three-dimensional space can exceed the density π/(3√2) ≈ 0.7405, achieved by the face-centered cubic (FCC) and hexagonal close-packed (HCP) lattices. Thomas Hales and Samuel Ferguson confirmed this in 1998 with an intricate computer-assisted proof, which the Annals of Mathematics published in 2005 after years of refereeing. The result was placed beyond doubt when the Flyspeck project, using the HOL Light and Isabelle proof assistants, completed a full formal verification published in Forum of Mathematics, Pi in 2017.",
  vizComponent: "SpherePackingViz",
  collections: ["canonical", "beautiful"],
  coordinates: {
      difficulty: 9,
      beauty: 9,
      visual: 10,
      importance: 8,
      activity: 6,
      accessibility: 8,
    },
  consensusStatus: "settled",
  lastReviewed: "2026-04",
  connections: ["Sphere packing", "Discrete geometry", "Formal proof"],
  authors: [
      {
        name: "Johannes Kepler",
        institution: "Imperial Mathematician, Prague",
        wikipediaUrl: "https://en.wikipedia.org/wiki/Johannes_Kepler",
      },
      {
        name: "Thomas C. Hales",
        institution: "University of Pittsburgh",
        wikipediaUrl: "https://en.wikipedia.org/wiki/Thomas_Callister_Hales",
      },
      {
        name: "Samuel P. Ferguson",
        institution: "University of Michigan (PhD student of Hales)",
      },
    ],
  papers: [
      {
        title: "A proof of the Kepler conjecture",
        arxivId: "math/9811071",
        url: "https://doi.org/10.4007/annals.2005.162.1065",
        year: 2005,
      },
      {
        title: "A formal proof of the Kepler conjecture",
        arxivId: "1501.02155",
        url: "https://doi.org/10.1017/fmp.2017.1",
        year: 2017,
      },
      {
        title: "A conceptual breakthrough in sphere packing",
        arxivId: "1611.01685",
        url: "https://doi.org/10.1090/noti1474",
        year: 2017,
      },
    ],
  videos: [
    {
      title: "The Best Way to Pack Spheres - Numberphile",
      videoId: "CROeIGfr3gs",
      channel: "Numberphile",
    },
    {
      title: "Calculating the optimal sphere packing density: with oranges",
      videoId: "3inLMXcetUA",
      channel: "Stand-up Maths",
    },
  ],
  timeline: [
      {
        year: 1611,
        title: "Kepler states the sphere-packing conjecture",
        description:
          "In Strena seu de Nive Sexangula (The Six-Cornered Snowflake), Kepler conjectures that FCC is the densest way to stack equal spheres.",
        type: "origin",
      },
      {
        year: 1831,
        title: "Gauss proves the lattice case",
        description:
          "Carl Friedrich Gauss proves that FCC is the densest lattice packing of spheres, leaving irregular arrangements open.",
        type: "progress",
      },
      {
        year: 1953,
        title: "Fejes Tóth reduces the problem to a finite computation",
        description:
          "László Fejes Tóth shows the conjecture can in principle be settled by checking finitely many local configurations.",
        type: "progress",
      },
      {
        year: 1998,
        month: "Aug",
        title: "Hales and Ferguson announce a proof",
        description:
          "Thomas Hales, assisted by graduate student Samuel Ferguson, completes a 250-page computer-aided proof.",
        type: "breakthrough",
      },
      {
        year: 2005,
        title: "Annals of Mathematics publishes the proof",
        description:
          "After six years of refereeing, the journal publishes Hales' 100-page article, noting the referees were 99% certain of correctness.",
        type: "recognition",
      },
      {
        year: 2017,
        title: "Flyspeck formal verification published",
        description:
          "Hales and 21 collaborators publish a machine-checked proof in Forum of Mathematics, Pi, using HOL Light and Isabelle.",
        type: "recognition",
      },
    ],
  formulas: [
    {
      label: "Maximum density",
      latex: String.raw`\delta_{\max}=\frac{\pi}{3\sqrt{2}}=\frac{\pi}{\sqrt{18}}\approx0.74048`,
      description:
        "The densest packing of unit spheres in R³ has this density, achieved by both FCC and HCP arrangements.",
    },
    {
      label: "FCC lattice vectors",
      latex: String.raw`\mathbf{a}_1=\tfrac{a}{2}(0,1,1),\quad \mathbf{a}_2=\tfrac{a}{2}(1,0,1),\quad \mathbf{a}_3=\tfrac{a}{2}(1,1,0)`,
      description:
        "The face-centered cubic lattice is generated by these three basis vectors; each sphere touches 12 neighbors (kissing number).",
    },
    {
      label: "Packing density definition",
      latex: String.raw`\delta=\lim_{r\to\infty}\frac{\operatorname{vol}\bigl(\bigcup_i B_i\cap B(0,r)\bigr)}{\operatorname{vol}\bigl(B(0,r)\bigr)}`,
      description:
        "The density of a sphere packing is the fraction of space covered, taken as a limit over growing regions.",
    },
  ]
});

export default keplerConjecture;
